---
- hosts: webserver
  gather_facts: no
  
  vars:
    # Hostname do servidor
    srv_hostname: ansible
    # Adicione o IP do seu servidor ou o domínio do site (caso já esteja publicado)
    # Após o provisionamento você poderá acessar o endereço para acessar a página web
    domain_site: 192.168.10.100

  roles:
    - provisioning
    - mysql
    - php
    - nginx