---
# tasks file for roles/php
- name: Adicionando PPA para instalação do PHP {{ php_version }}
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Instalando PHP-FPM {{ php_version }}
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php-memcached
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-pgsql"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-bz2"
      - "php{{ php_version }}-zip"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-interbase"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-bcmath"
      - "php{{ php_version }}-soap"
      - "php{{ php_version }}-snmp"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-xmlrpc"
      - "php{{ php_version }}-xsl"

- name: Seta date.timezone
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = {{ php_timezone }}"

- name: Seta cgi.fix_pathinfo
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "cgi.fix_pathinfo="
    line: "cgi.fix_pathinfo = 0"

- name: Seta max_execution_time
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "max_execution_time ="
    line: "max_execution_time = 180"

- name: Seta max_input_time
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "max_input_time ="
    line: "max_input_time = 180"

- name: Seta memory_limit
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "memory_limit ="
    line: "memory_limit = 256M"

- name: Seta post_max_size
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "post_max_size ="
    line: "post_max_size = 128M"

- name: Seta upload_max_filesize
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "upload_max_filesize ="
    line: "upload_max_filesize = 128M"

- name: Seta max_file_uploads
  lineinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    regexp: "max_file_uploads ="
    line: "max_file_uploads = 128"
  notify: restart php-fpm
